P2 132 endpoint pickers
LangaraVoyagers/project-2-api pull request #14
Opened 2024-02-21 00:14 UTC by ALFAROSO

https://team-voyagers.atlassian.net/jira/software/projects/P2/boards/2?selectedIssue=P2-145

2024-02-22 16:56 UTC, whamester requested changes

2024-02-22 19:06 UTC, whamester approved these changes

2024-02-22 19:43 UTC, ReinhardtBotha reviewed
is the responses following the backend standard?

`GET All will return an array, no message `
 
`GET by Id will return an object, no message `
 
```
POST, PUT, and DELETE 
{ 
    message, 
    data, 
    error, 
} 
```

2024-02-22 23:54 UTC, ReinhardtBotha approved these changes
endpoints working as expected.

2024-02-23 03:43 UTC, BryanCaldeira approved these changes
✅

2024-02-23 04:50 UTC, merged