156 bug sms decimal numbers
LangaraVoyagers/project-2-api pull request #45
Opened 2024-04-03 20:26 UTC by ALFAROSO

![WhatsApp Image 2024-04-03 at 1 23 39 PM](https://github.com/LangaraVoyagers/project-2-api/assets/87240930/419ba2d4-7d98-443a-9565-b8d050e813c8)

2024-04-03 20:41 UTC, ALFAROSO commented
![WhatsApp Image 2024-04-03 at 1 40 40 PM](https://github.com/LangaraVoyagers/project-2-api/assets/87240930/616aef77-9c9e-4d30-b50e-27cecb57bac4)

2024-04-03 21:01 UTC, ReinhardtBotha requested changes
When it comes to money, we use 2 decimals. Can you please change it to round to 2 decimals?

2024-04-03 22:07 UTC, whamester approved these changes

2024-04-04 02:08 UTC, ReinhardtBotha approved these changes
✅

2024-04-04 02:54 UTC, BryanCaldeira approved these changes

2024-04-04 03:03 UTC, merged